"use client";

import { useEffect, useState } from "react";
import { WordleGame } from "@/components/WordleGame";
import { phonemeHint } from "@/lib/phonemes";
import { generateWordleHtml } from "@/lib/exportWordle";
import { ApiError, fetchAllActivities, generateActivity, type Activity, type ApiWord } from "@/lib/api";

type LoadState =
  | { status: "loading" }
  | { status: "error"; message: string }
  | { status: "ready"; activityId: string; word: ApiWord; hints: Record<string, string> };

export default function WordlePage() {
  const [activities, setActivities] = useState<Activity[]>([]);
  const [selectedId, setSelectedId] = useState<string>("");
  const [state, setState] = useState<LoadState>({ status: "loading" });

  async function loadActivityList() {
    setState({ status: "loading" });
    try {
      const all = await fetchAllActivities();
      const wordleActivities = all.filter((a) => a.type === "WORDLE");
      setActivities(wordleActivities);
      if (wordleActivities.length === 0) {
        setState({ status: "error", message: "No Wordle activity has been configured yet." });
        return;
      }
      const id = wordleActivities.some((a) => a.id === selectedId) ? selectedId : wordleActivities[0].id;
      setSelectedId(id);
      await loadGeneratedWord(id);
    } catch (err) {
      setState({
        status: "error",
        message: err instanceof ApiError ? err.message : "Failed to load the Wordle activity.",
      });
    }
  }

  async function loadGeneratedWord(activityId: string) {
    setState({ status: "loading" });
    try {
      const generated = await generateActivity(activityId);
      setState({
        status: "ready",
        activityId,
        word: generated.words[0],
        hints: generated.hints,
      });
    } catch (err) {
      setState({
        status: "error",
        message: err instanceof ApiError ? err.message : "Failed to load the Wordle activity.",
      });
    }
  }

  function handleActivityChange(id: string) {
    setSelectedId(id);
    loadGeneratedWord(id);
  }

  useEffect(() => {
    // eslint-disable-next-line react-hooks/set-state-in-effect
    loadActivityList();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  function handleDownload() {
    if (state.status !== "ready") return;
    const html = generateWordleHtml(state.word);
    const blob = new Blob([html], { type: "text/html" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "phoneme-wordle.html";
    document.body.appendChild(a);
    a.click();
    a.remove();
    URL.revokeObjectURL(url);
  }

  return (
    <div className="mx-auto flex w-full max-w-4xl flex-1 flex-col gap-8 px-4 py-12 sm:px-6">
      <div>
        <h2 className="text-3xl font-bold text-zinc-900 dark:text-zinc-50">
          Wordle Builder
        </h2>
        <p className="mt-2 max-w-2xl text-zinc-700 dark:text-zinc-300">
          The target word is generated by the backend from the saved word
          list each time you load or reset this page. Build guesses using
          the phoneme keyboard &mdash; each button shows a spelled letter
          equivalent, and hovering shows the phonetic symbol and sound.
        </p>
      </div>

      {activities.length > 0 && (
        <div className="rounded-xl border border-zinc-200 bg-white p-5 dark:border-zinc-800 dark:bg-zinc-950">
          <label className="flex flex-col text-sm text-zinc-700 dark:text-zinc-300">
            Activity
            <select
              value={selectedId}
              onChange={(e) => handleActivityChange(e.target.value)}
              className="mt-1 w-full max-w-sm rounded-md border border-zinc-300 px-3 py-2 text-zinc-900 dark:border-zinc-700 dark:bg-zinc-900 dark:text-zinc-100 sm:w-auto"
            >
              {activities.map((a) => (
                <option key={a.id} value={a.id}>
                  {a.title} ({a.wordList.name})
                </option>
              ))}
            </select>
          </label>
        </div>
      )}

      <div className="rounded-xl border border-zinc-200 bg-white p-5 dark:border-zinc-800 dark:bg-zinc-950">
        {state.status === "loading" && (
          <p className="text-sm text-zinc-500 dark:text-zinc-400">Loading activity…</p>
        )}

        {state.status === "error" && (
          <div className="rounded-lg border border-red-200 bg-red-50 p-4 text-sm text-red-800 dark:border-red-900 dark:bg-red-950 dark:text-red-300">
            <p>{state.message}</p>
            <button
              type="button"
              onClick={loadActivityList}
              className="mt-3 rounded-full border border-red-300 bg-white px-4 py-1.5 text-xs font-semibold text-red-700 hover:bg-red-100 dark:border-red-800 dark:bg-red-950 dark:text-red-300 dark:hover:bg-red-900"
            >
              Try again
            </button>
          </div>
        )}

        {state.status === "ready" && (
          <>
            <WordleGame key={state.word.id} word={state.word} />
            <div className="mt-6 flex justify-center">
              <button
                type="button"
                onClick={() => loadGeneratedWord(selectedId)}
                className="rounded-full border border-zinc-300 bg-white px-4 py-2 text-sm font-medium text-zinc-900 hover:bg-zinc-100 dark:border-zinc-700 dark:bg-zinc-900 dark:text-zinc-100 dark:hover:bg-zinc-800"
              >
                New word
              </button>
            </div>
          </>
        )}
      </div>

      {state.status === "ready" && (
        <div className="rounded-xl border border-zinc-200 bg-zinc-50 p-5 dark:border-zinc-800 dark:bg-zinc-950">
          <h3 className="font-semibold text-zinc-900 dark:text-zinc-50">
            Phoneme hint legend
          </h3>
          <p className="mt-1 text-sm text-zinc-600 dark:text-zinc-400">
            Example: a keyboard button labelled TH represents{" "}
            <span className="font-mono">/θ/</span>.
          </p>
          <ul className="mt-3 flex flex-wrap gap-2">
            {state.word.phonemes.map((symbol) => (
              <li
                key={symbol}
                title={state.hints[symbol]}
                className="rounded-md border border-zinc-200 bg-white px-3 py-1 text-sm dark:border-zinc-800 dark:bg-zinc-900"
              >
                <span className="font-mono font-semibold">/{symbol}/</span>{" "}
                <span className="text-zinc-500 dark:text-zinc-400">
                  {state.hints[symbol] ?? phonemeHint(symbol)}
                </span>
              </li>
            ))}
          </ul>
        </div>
      )}

      <div>
        <button
          type="button"
          onClick={handleDownload}
          disabled={state.status !== "ready"}
          className="rounded-full bg-green-700 px-6 py-3 text-sm font-semibold text-white hover:bg-green-800 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-green-600 disabled:cursor-not-allowed disabled:opacity-50"
        >
          Generate &amp; download HTML
        </button>
        <p className="mt-2 text-sm text-zinc-500 dark:text-zinc-400">
          Downloads this Wordle activity as a single standalone .html file.
        </p>
      </div>
    </div>
  );
}
